// Planet Data - Complete Solar System Information
const planetData = {
  sun: {
    name: "Sun",
    type: "G-type Main-sequence Star",
    color: 0xffdd00,
    emissive: 0xffaa00,
    size: 15,
    orbitRadius: 0,
    orbitSpeed: 0,
    rotationSpeed: 0.001,
    diameter: "1,392,700 km",
    distance: "0 km (Center)",
    orbitalPeriod: "N/A",
    dayLength: "25-35 Earth days",
    moons: "N/A",
    temperature: "5,500°C (Surface)",
    composition: "Hydrogen (73%), Helium (25%), Other elements (2%)",
    description:
      "The Sun is the star at the center of our Solar System. It is a nearly perfect sphere of hot plasma, heated to incandescence by nuclear fusion reactions in its core. The Sun radiates energy mainly as light, ultraviolet, and infrared radiation, and is the most important source of energy for life on Earth.",
    facts: [
      "The Sun contains 99.86% of the mass in the Solar System",
      "Light from the Sun takes 8 minutes 20 seconds to reach Earth",
      "The Sun's core temperature is about 15 million degrees Celsius",
      "One million Earths could fit inside the Sun",
      "The Sun is about 4.6 billion years old",
    ],
    gradient: "radial-gradient(circle, #ffd700, #ff8c00, #ff4500)",
    texture: "textures/sun.jpg",
  },
  mercury: {
    name: "Mercury",
    type: "Terrestrial Planet",
    color: 0xb5b5b5,
    size: 0.8,
    orbitRadius: 25,
    orbitSpeed: 0.04,
    rotationSpeed: 0.005,
    diameter: "4,879 km",
    distance: "57.9 million km",
    orbitalPeriod: "88 Earth days",
    dayLength: "59 Earth days",
    moons: "0",
    temperature: "-180°C to 430°C",
    composition: "Iron-rich core (70% metallic), Silicate mantle (30%)",
    description:
      "Mercury is the smallest and innermost planet in the Solar System. It has no natural satellites and no substantial atmosphere. The planet has a heavily cratered surface similar to Earth's Moon, but with unique features like scarps (cliffs) that formed as the planet's interior cooled and contracted.",
    facts: [
      "Mercury has the most extreme temperature variations of any planet",
      "A year on Mercury is just 88 Earth days",
      "Mercury has ice in permanently shadowed craters near its poles",
      "Despite being closest to the Sun, it's not the hottest planet",
      "Mercury's surface is covered with impact craters",
    ],
    gradient: "radial-gradient(circle, #b5b5b5, #8c8c8c, #5c5c5c)",
    texture: "textures/mercury.jpg",
  },
  venus: {
    name: "Venus",
    type: "Terrestrial Planet",
    color: 0xffd699,
    size: 1.2,
    orbitRadius: 35,
    orbitSpeed: 0.015,
    rotationSpeed: -0.002,
    diameter: "12,104 km",
    distance: "108.2 million km",
    orbitalPeriod: "225 Earth days",
    dayLength: "243 Earth days",
    moons: "0",
    temperature: "465°C (Average)",
    composition: "Iron core, Rocky mantle, Dense CO₂ atmosphere",
    description:
      "Venus is the second planet from the Sun and is Earth's closest planetary neighbor. It's often called Earth's twin because of their similar size and mass. However, Venus has a thick, toxic atmosphere filled with carbon dioxide and clouds of sulfuric acid, making it the hottest planet in our solar system.",
    facts: [
      "Venus rotates backwards compared to most planets",
      "A day on Venus is longer than its year",
      "Venus is the hottest planet in our solar system",
      "The atmospheric pressure is 90 times that of Earth",
      "Venus has over 1,600 major volcanoes",
    ],
    gradient: "radial-gradient(circle, #ffd699, #e6ac00, #cc8800)",
    texture: "textures/venus.jpg",
  },
  earth: {
    name: "Earth",
    type: "Terrestrial Planet",
    color: 0x6b93d6,
    size: 1.3,
    orbitRadius: 50,
    orbitSpeed: 0.01,
    rotationSpeed: 0.02,
    diameter: "12,742 km",
    distance: "149.6 million km (1 AU)",
    orbitalPeriod: "365.25 days",
    dayLength: "24 hours",
    moons: "1 (Moon)",
    temperature: "15°C (Average)",
    composition:
      "Iron core, Silicate mantle, Water oceans (71%), Nitrogen-oxygen atmosphere",
    description:
      "Earth is the third planet from the Sun and the only astronomical object known to harbor life. About 71% of Earth's surface is water, mostly in the form of oceans. Earth's atmosphere is rich in nitrogen and oxygen, and its magnetic field protects life from harmful solar radiation.",
    facts: [
      "Earth is the only planet not named after a god",
      "Earth's rotation is gradually slowing down",
      "70% of Earth's surface is covered in water",
      "Earth has a powerful magnetic field",
      "The Earth's core is as hot as the Sun's surface",
    ],
    gradient: "radial-gradient(circle, #6b93d6, #4f7942, #2d5016)",
    texture: "textures/earth.jpg",
    cloudTexture: "textures/earth_clouds.jpg",
  },
  mars: {
    name: "Mars",
    type: "Terrestrial Planet",
    color: 0xe27b58,
    size: 1,
    orbitRadius: 70,
    orbitSpeed: 0.008,
    rotationSpeed: 0.018,
    diameter: "6,779 km",
    distance: "227.9 million km",
    orbitalPeriod: "687 Earth days",
    dayLength: "24.6 hours",
    moons: "2 (Phobos, Deimos)",
    temperature: "-65°C (Average)",
    composition:
      "Iron core, Silicate rock, Iron oxide surface (rust), Thin CO₂ atmosphere",
    description:
      "Mars is the fourth planet from the Sun and the second-smallest planet in the Solar System. It's often called the 'Red Planet' because of its reddish appearance caused by iron oxide on its surface. Mars has the largest volcano and canyon in the solar system - Olympus Mons and Valles Marineris.",
    facts: [
      "Mars has the largest volcano in the solar system - Olympus Mons",
      "Mars has seasons like Earth due to its tilted axis",
      "A day on Mars is only slightly longer than on Earth",
      "Mars has polar ice caps made of water and carbon dioxide",
      "The red color comes from iron oxide (rust) on its surface",
    ],
    gradient: "radial-gradient(circle, #e27b58, #c1440e, #8b2500)",
    texture: "textures/mars.jpg",
  },
  jupiter: {
    name: "Jupiter",
    type: "Gas Giant",
    color: 0xd8ca9d,
    size: 5,
    orbitRadius: 100,
    orbitSpeed: 0.002,
    rotationSpeed: 0.04,
    diameter: "139,820 km",
    distance: "778.5 million km",
    orbitalPeriod: "11.86 Earth years",
    dayLength: "9.93 hours",
    moons: "95 known moons",
    temperature: "-110°C (Cloud tops)",
    composition: "Hydrogen (90%), Helium (10%), Rocky core",
    description:
      "Jupiter is the fifth planet from the Sun and the largest in the Solar System. It is a gas giant with a mass more than two and a half times that of all the other planets combined. Jupiter's iconic Great Red Spot is a giant storm that has been observed for over 400 years.",
    facts: [
      "Jupiter has the shortest day of all planets",
      "The Great Red Spot is a storm larger than Earth",
      "Jupiter has the strongest magnetic field of any planet",
      "Jupiter's moon Ganymede is the largest moon in the solar system",
      "Jupiter acts as a cosmic vacuum cleaner, protecting Earth from asteroids",
    ],
    gradient: "radial-gradient(circle, #d8ca9d, #b5a76c, #8b7355)",
    texture: "textures/jupiter.jpg",
  },
  saturn: {
    name: "Saturn",
    type: "Gas Giant",
    color: 0xf4d59e,
    size: 4.5,
    orbitRadius: 140,
    orbitSpeed: 0.0009,
    rotationSpeed: 0.038,
    hasRings: true,
    ringColor: 0xc9a227,
    diameter: "116,460 km",
    distance: "1.4 billion km",
    orbitalPeriod: "29.46 Earth years",
    dayLength: "10.7 hours",
    moons: "146 known moons",
    temperature: "-140°C (Cloud tops)",
    composition: "Hydrogen (96%), Helium (3%), Rocky/icy core",
    description:
      "Saturn is the sixth planet from the Sun and the second-largest in the Solar System. It is best known for its spectacular ring system, which is made up of ice and rock particles. Saturn is a gas giant with an average radius about nine times that of Earth.",
    facts: [
      "Saturn's rings are made of ice and rock",
      "Saturn could float in water (if there was a bathtub big enough)",
      "Saturn has 146 known moons, including Titan with its own atmosphere",
      "Saturn's rings span up to 282,000 km but are only 10m thick",
      "Winds on Saturn can reach 1,800 km/h",
    ],
    gradient: "radial-gradient(circle, #f4d59e, #c9a227, #8b6914)",
    texture: "textures/saturn.jpg",
    ringTexture: "textures/saturn_ring.jpg",
  },
  uranus: {
    name: "Uranus",
    type: "Ice Giant",
    color: 0xd1e7e7,
    size: 2.5,
    orbitRadius: 180,
    orbitSpeed: 0.0004,
    rotationSpeed: -0.03,
    hasRings: true,
    ringColor: 0x4fd0e7,
    tilt: Math.PI / 2,
    diameter: "50,724 km",
    distance: "2.9 billion km",
    orbitalPeriod: "84 Earth years",
    dayLength: "17.2 hours",
    moons: "27 known moons",
    temperature: "-195°C",
    composition: "Water, methane, ammonia ices, Hydrogen-helium atmosphere",
    description:
      "Uranus is the seventh planet from the Sun. It has the third-largest planetary radius and fourth-largest planetary mass in the Solar System. Uranus is unique for rotating on its side, with its axis of rotation tilted at 98 degrees. This may have been caused by a collision with an Earth-sized object long ago.",
    facts: [
      "Uranus rotates on its side at a 98-degree tilt",
      "Uranus was the first planet discovered using a telescope",
      "Uranus has 13 known rings",
      "A season on Uranus lasts 21 Earth years",
      "Uranus is the coldest planetary atmosphere in the solar system",
    ],
    gradient: "radial-gradient(circle, #d1e7e7, #4fd0e7, #1e90af)",
    texture: "textures/uranus.jpg",
  },
  neptune: {
    name: "Neptune",
    type: "Ice Giant",
    color: 0x5b5ddf,
    size: 2.4,
    orbitRadius: 220,
    orbitSpeed: 0.0001,
    rotationSpeed: 0.032,
    diameter: "49,244 km",
    distance: "4.5 billion km",
    orbitalPeriod: "164.8 Earth years",
    dayLength: "16.1 hours",
    moons: "16 known moons",
    temperature: "-200°C",
    composition: "Water, methane, ammonia ices, Hydrogen-helium atmosphere",
    description:
      "Neptune is the eighth and farthest-known Solar planet from the Sun. In the Solar System, it is the fourth-largest planet by diameter, the third-most-massive planet, and the densest giant planet. Neptune's atmosphere is notable for its vivid blue color and supersonic wind speeds.",
    facts: [
      "Neptune has the strongest winds in the solar system (2,100 km/h)",
      "Neptune was predicted mathematically before being observed",
      "Neptune's moon Triton orbits in the opposite direction",
      "Neptune has completed only one orbit since its discovery in 1846",
      "Neptune's blue color comes from methane in its atmosphere",
    ],
    gradient: "radial-gradient(circle, #5b5ddf, #3e54e8, #1e3a8a)",
    texture: "textures/neptune.jpg",
  },
};

// Planet colors for 3D rendering
const planetColors = {
  sun: 0xffdd00,
  mercury: 0xb5b5b5,
  venus: 0xffd699,
  earth: 0x6b93d6,
  mars: 0xe27b58,
  jupiter: 0xd8ca9d,
  saturn: 0xf4d59e,
  uranus: 0xd1e7e7,
  neptune: 0x5b5ddf,
};

// Atmosphere colors
const atmosphereColors = {
  earth: 0x87ceeb,
  venus: 0xffc649,
  mars: 0xffaa00,
  jupiter: 0xd8ca9d,
  saturn: 0xf4d59e,
  uranus: 0x4fd0e7,
  neptune: 0x5b5ddf,
};
